sudo: required
services:
  - docker
before_install:
  - docker build -t rohitpandey33/docker_react:latest -f Dockerfile .
script:
  - docker run rohitpandey33/docker_react npm run test -- --watchAll=false
